---
- name: Configuring tomcat9
  hosts: all
  tasks:
   - name: Install tomcat9
     apt:
      name: tomcat9
      state: present
      update_cache: yes
   - name: Copy the tomcat-users.xml
     copy:
      src: tomcat-users.xml
      dest: /etc/tomcat9
   - name: Change port of tomcat from 8080 to 9090
     replace:
      regexp: 8080
      replace: 9090
      path: /etc/tomcat9/server.xml
   - name: Restart tomcat9
     service:
      name: tomcat9
      state: restarted
   - name: Pause for 1 minute
     pause:
      minutes: 1
   - name: Check response of tomcat on server1
     uri:
      url: http://172.31.9.139:9090
      status_code: 200
   - name: Check url response of tomcat on server2
     uri:
      url: http://172.31.2.201:9090
      status_code: 200

