- name: checking service status
  hosts: all
  tasks:
  - name: checking service status
    command: systemctl status "{{ item }}"
    with_items:
     - tomcat9
    register: result
    ignore_errors: yes
  - name: showing report
    debug:
     var: result

